# Generated by Django 4.2.11 on 2026-01-08 07:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthIdentity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=20)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_identities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('problem_id', models.IntegerField(primary_key=True, serialize=False)),
                ('problem', models.TextField()),
                ('difficulty', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('algorithm', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coding_problem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CodingProblemLanguage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('function_name', models.CharField(max_length=255)),
                ('starter_code', models.TextField()),
                ('language', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'coding_problem_language',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LivecodingReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('report_md', models.TextField()),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('final_grade', models.CharField(blank=True, max_length=8, null=True)),
                ('graph_output', models.JSONField(default=dict)),
                ('problem', models.JSONField(blank=True, default=dict, null=True)),
                ('code_feedback', models.TextField(blank=True, null=True)),
                ('problem_solving_evaluation', models.JSONField(blank=True, null=True)),
                ('initial_strategy', models.TextField(blank=True, null=True)),
                ('approach_validity', models.TextField(blank=True, null=True)),
                ('consistency_status', models.TextField(blank=True, null=True)),
                ('consistency_feedback', models.TextField(blank=True, null=True)),
                ('submitted_code', models.TextField(blank=True, null=True)),
                ('annotated_code', models.TextField(blank=True, null=True)),
                ('strength', models.TextField(blank=True, null=True)),
                ('improvement', models.TextField(blank=True, null=True)),
                ('comprehensive_evaluation', models.TextField(blank=True, null=True)),
                ('anti_cheat_summary', models.JSONField(blank=True, null=True)),
                ('problem_eval_score', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('problem_eval_feedback', models.TextField(blank=True, null=True)),
                ('code_collab_score', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('code_collab_feedback', models.TextField(blank=True, null=True)),
                ('problem_evidence', models.JSONField(blank=True, null=True)),
                ('code_collab_evidence', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'livecoding_reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=200)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'profile_option',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('input_data', models.TextField(db_column='input')),
                ('output_data', models.TextField(db_column='output')),
            ],
            options={
                'db_table': 'test_case',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(db_column='user_id', max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_verifications',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('graduated_school', models.CharField(blank=True, max_length=100, null=True)),
                ('university', models.CharField(blank=True, max_length=200, null=True)),
                ('major', models.CharField(blank=True, max_length=20, null=True)),
                ('academic_status', models.CharField(blank=True, max_length=20, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('career_level', models.CharField(blank=True, max_length=50, null=True)),
                ('current_status', models.CharField(blank=True, max_length=50, null=True)),
                ('tech_stack', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('desired_role', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('detailed_role', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('region', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserGrowthInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('version', models.IntegerField()),
                ('window_size', models.IntegerField(default=3)),
                ('report_ids', models.JSONField(default=list)),
                ('report_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_growth_insight',
                'indexes': [models.Index(fields=['user_id', '-version'], name='user_growth_user_id_d72dee_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='usergrowthinsight',
            constraint=models.UniqueConstraint(fields=('user_id', 'version'), name='uq_user_version'),
        ),
    ]
