# Generated by Django 4.2.11 on 2026-01-08 07:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_lang', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('video_url', models.URLField()),
                ('summary', models.TextField()),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('domain', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recommended_videos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('duration', models.IntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('topic', models.CharField(max_length=255)),
                ('video_id', models.IntegerField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('is_completed', models.CharField(blank=True, max_length=30, null=True)),
                ('why_selected', models.CharField(blank=True, max_length=255, null=True)),
                ('lecture_note', models.CharField(blank=True, default='')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='planner.studyplan')),
            ],
        ),
    ]
